apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: hello-minikube-test-app   # Match this label with the Deployment template
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube-test-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-minikube-test-app   # Match this label with the Service selector
  template:
    metadata:
      labels:
        app: hello-minikube-test-app   # Make sure this matches the Service selector
    spec:
      containers:
        - name: followerscount-container   # Use a descriptive name for the container
          image: collinskiprotich780/followerscount
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
